#################################
# --- Required parameters ----#

# Path to sample sheet; see README for details.
path_samples: "~/jvanriet/git/snakemake-sciseq/workflow/examples/example_samplesheet.tsv"

# Path to barcode files for demultiplexing. See examples/barcodes.tsv for an example and README for details.
path_barcodes: "~/jvanriet/git/snakemake-sciseq/workflow/examples/barcodes.tsv"

# Path to the output folder.
dir_output: "/omics/groups/OE0538/internal/projects/sexomics/runJob/"

# Path to fasta and GTF file containing the main reference genome and annotations.
# The identifier (e.g. Mouse) is used to identify the species as specified in the sample sheet.
species:
  mouse:
    genome: "/omics/groups/OE0538/internal/projects/sharedData/GRCm39/genome/GRCm39.primary_assembly.genome.fa"
    genome_gtf: "/omics/groups/OE0538/internal/projects/sharedData/GRCm39/annotation/gencode.vM31.basic.annotation.gtf"
  human:
    genome: "/omics/groups/OE0538/internal/projects/sharedData/hsapiens/genome/xxx.fa"
    genome_gtf: "/omics/groups/OE0538/internal/projects/sharedData/hsapiens/annotation/xxx.gtf"

#################################
# --- Additional parameters ----#
settings:
  # Number of splitted .fastq.gz files to generate per sequencing run to parallize the demultiplexing.
  scatter_fastq_split: 20
  fastp: "--qualified_quality_phred 15 --dont_eval_duplication --dup_calc_accuracy 3 --length_required 10"
  star: ""
