#################################
# --- Required parameters ----#

# Path to sample sheet; see README for details.
path_samples: "/omics/groups/OE0538/internal/projects/LesionSegregration_F1/metadata/SupplTable1_OverviewSequencing.xlsx"

# Path to the folder containing the (raw/untrimmed) fastq files.
dir_fastq: "/omics/groups/OE0538/internal/projects/LesionSegregration_F1/data/rawreads"  

# Path to the output folder.
dir_output: "/omics/groups/OE0538/internal/projects/LesionSegregration_F1/results/"

# Path to temporary folder for storing the intermediates of several large processes.
dir_tmp: "/omics/groups/OE0538/internal/projects/LesionSegregration_F1/data/tmp/"

# Path to fasta and GTF file containing the main reference genome and annotations.
# The identifier (e.g. Mouse) is used to identify the species as specified in the sample sheet.
species:
  mouse:
    genome: "/omics/groups/OE0538/internal/projects/sharedData/GRCm39/genome/GRCm39.primary_assembly.genome.fa"
    genome_gtf: "/omics/groups/OE0538/internal/projects/sharedData/GRCm39/annotation/gencode.vM31.basic.annotation.gtf"
  human:
    genome: "/omics/groups/OE0538/internal/projects/sharedData/hsapiens/genome/xxx.fa"
    genome_gtf: "/omics/groups/OE0538/internal/projects/sharedData/hsapiens/annotation/xxx.gtf"


# Path to barcode files for demultiplexing. See examples/barcodes.tsv for an example.
# Format (TSV): name barcode_sequence
path_barcodes: examples/barcodes.tsv"

#################################
# --- Additional parameters ----#
settings:
  fastp: "--qualified_quality_phred 15 --dont_eval_duplication --dup_calc_accuracy 3 --length_required 10"
  star: ""
