#################################
# --- Required parameters ----#

# Path to sample sheet; see README for details.
path_samples: "examples/example_samplesheet.tsv"

# Path to barcode files for demultiplexing. See examples/barcodes.tsv for an example and README for details.
path_barcodes: "examples/barcodes.tsv"

# Path to the output folder.
dir_output: "examples/test_output/"

# Path to fasta and GTF file containing the main reference genome and annotations.
# The identifier (e.g. Mouse) is used to identify the species as specified in the sample sheet.
# star_index (path) is optional and can be set to False if no STAR index is already available (this will be generated as part of the workflow).
species:
  mouse:
    genome: "xxx.fa"
    genome_gtf: "xxx.gtf"
    star_index: False
  human:
    genome: "xxx.fa"
    genome_gtf: "xxx.gtf"
    star_index: False

#################################
# --- Additional parameters ----#

# Read length of R2 (i.e. the read containing the cDNA sequence) - 1.
# This is used during genome generation to set the --sjdbOverhang parameter.
length_R2: 83

settings:
  # Number of splitted .fastq.gz files to generate per sequencing run to parallize the demultiplexing.
  scatter_fastq_split: 10
  # Custom settings for bcl2fastq.
  bcl2fastq: ""
  # Custom settings for fastp.
  fastp: ""
  # Custom settings for STAR genome preparation.
  star_index: ""
  # Custom settings for STARSolo alignment.
  star: ""
