#################################
# --- Required parameters ----#

# Path to sample sheet; see README for details.
path_samples: "examples/example_samplesheet.tsv"

# Path to barcode files for demultiplexing. See examples/barcodes.tsv for an example and README for details.
path_barcodes: "examples/example_barcodes.tsv"

# Path to the output folder.
dir_output: "examples/test_output/"

# Path to fasta and GTF file containing the main reference genome and annotations.
# The identifier (e.g. mouse) is used to identify the species as specified in the sample sheet.
# star_index (path) is optional and can be set to False if no STAR index is already available (this will be generated as part of the workflow).
species:
  mouse:
    genome: "xxx.fa"
    genome_gtf: "xxx.gtf"
    star_index: False
  zebrafish:
    genome: "xxx.fa"
    genome_gtf: "xxx.gtf"
    star_index: False

#################################
# --- Additional parameters ----#

# Custom settings for various major steps of the workflow.
# Important: (star_index): Change the --sjdbOverhang parameter to the read length of R2 (i.e. the read containing the cDNA sequence) - 1.
# Important: (star_index): For example, if R2 is 84bp long, then --sjdbOverhang should be set to 83.
settings:
  # Number of splitted .fastq.gz files to generate per sequencing run to parallize the demultiplexing.
  scatter_fastq_split: 10
  # Custom settings for bcl2fastq.
  bcl2fastq: "--barcode-mismatches 1 --ignore-missing-positions --ignore-missing-controls --ignore-missing-filter --ignore-missing-bcls --no-lane-splitting --minimum-trimmed-read-length 15 --mask-short-adapter-reads 15"
  # Custom settings for fastp.
  fastp: "--detect_adapter_for_pe --qualified_quality_phred 15 --dont_eval_duplication --length_required 10"
  # Custom settings for STAR genome preparation.
  star_index: "--sjdbOverhang 83"
  # Custom settings for STARSolo alignment.
  star: "--soloFeatures GeneFull --soloCellReadStats Standard --soloMultiMappers EM --outSAMmultNmax 1 --outSAMstrandField intronMotif --outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33 --outSAMunmapped Within --outSAMattributes NH HI AS nM NM MD jM jI MC ch XS CR UR GX GN sM"