#################################
# --- Required parameters ----#

# Path to sample sheet; see README for details.
path_samples: "~/jvanriet/git/snakemake-sciseq/workflow/examples/example_samplesheet.tsv"

# Path to barcode files for demultiplexing. See examples/barcodes.tsv for an example and README for details.
path_barcodes: "~/jvanriet/git/snakemake-sciseq/workflow/examples/barcodes.tsv"

# Path to the output folder.
dir_output: "/omics/groups/OE0538/internal/projects/sexomics/runJob/"

# Path to fasta and GTF file containing the main reference genome and annotations.
# The identifier (e.g. Mouse) is used to identify the species as specified in the sample sheet.
# star_index (path) is optional and can be set to False if no STAR index is already available (this will be generated as part of the workflow).
species:
  mouse:
    genome: "/omics/groups/OE0538/internal/projects/sharedData/GRCm39/genome/GRCm39.primary_assembly.genome.fa"
    genome_gtf: "/omics/groups/OE0538/internal/projects/sharedData/GRCm39/annotation/gencode.vM31.basic.annotation.gtf"
    star_index: False
  human:
    genome: "xxx.fa"
    genome_gtf: "xxx.gtf"
    star_index: False

#################################
# --- Additional parameters ----#
settings:
  # Number of splitted .fastq.gz files to generate per sequencing run to parallize the demultiplexing.
  scatter_fastq_split: 20
  fastp: "--qualified_quality_phred 15 --dont_eval_duplication --length_required 10"
  star: "--outSAMstrandField intronMotif --outFilterMultimapNmax 10 --outFilterMismatchNmax 3 --limitOutSJcollapsed 3000000 --chimSegmentMin 10 --chimOutType WithinBAM SoftClip --chimJunctionOverhangMin 10 --chimSegmentReadGapMax 3 --chimScoreMin 1 --chimScoreDropMax 30 --chimScoreJunctionNonGTAG 0 --chimScoreSeparation 1 --outFilterScoreMinOverLread 0.33 --outFilterMatchNminOverLread 0.33 --outFilterMatchNmin 35 --alignSplicedMateMapLminOverLmate 0.33 --alignSplicedMateMapLmin 35 --alignSJstitchMismatchNmax 5 -1 5 5"
